export const constants = {
	COMPLETION_TRIGGER_DEFAULT_VALUE: ";;",
	TICKET_TAG_SEPARATOR_DEFAULT_VALUE: "---",
	TICKET_NUMBER_SEPARATOR_DEFAULT_VALUE: ": ",
	AUTOCOMPLETION_MINIMUM_CHARACTERS_DEFAULT_VALUE: 2,
}
